import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
export const metadata: Metadata = {
  title: "Ebubechukwu Chiemeka | Fullstack Developer",
  description:
    "Hey! Welcome to my portfolio. Feel free to check out my projects to see different styles and shades of my work. I’m a fullstack developer and an all-rounder — if you like what you see and want your website to look like one of these, hit me up.",
  openGraph: {
    title: "Ebubechukwu Chiemeka | Fullstack Developer",
    description:
      "Welcome to my portfolio! Explore different website styles, designs, and layouts that showcase my versatility as a fullstack developer. Let’s build something great together.",
    url: "https://portfolio-delta-three-24.vercel.app/",
    siteName: "Ebubechukwu Chiemeka Portfolio",
    images: [
      {
        url: "https://portfolio-delta-three-24.vercel.app/projects/landing.png",
        width: 1200,
        height: 630,
        alt: "Ebubechukwu Chiemeka Portfolio Preview",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Ebubechukwu Chiemeka | Fullstack Developer",
    description:
      "Check out my portfolio showcasing different website styles and designs. Fullstack developer ready to bring your ideas to life.",
    images: ["https://portfolio-delta-three-24.vercel.app/projects/landing.png"],
    site: "@Fatboy_Of_Web3",
    creator: "@Fatboy_Of_Web3",
  },
};
};
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-950 text-white">
        <Navbar/>
  {children}
</body>
    </html>
  );
}
